### ISSUE TITLE
Replace libraries in libraries/ with composer

### ISSUE THREAD

**Issue by IT-Solutions4You** [IT-Solutions4You/its4youcrm#5]
adodb - https://github.com/ADOdb
htmlpurifier410 - https://github.com/ezyang/htmlpurifier
PHPMarkdown- https://github.com/michelf/php-markdown
Smarty - https://github.com/smarty-php/smarty

To be discussed:

- csrf-magic is installable via composer: https://github.com/ezyang/csrf-magic, but it is not maintained anymore. Last change was 7 years ago. We can replace it with another library: https://github.com/mebjas/CSRF-Protector-PHP, which seems to be easy to use and was last changed two years ago. I did not found anything newer.

- google-api-php-client is installable via composer: https://github.com/googleapis/google-api-php-client, but it seems like in the crm is quite outdated version. The actual version has another structure, looks like it can be a bit complicated, but I do recommend it.

- HTTP_Session & HTTP_Session2: the "two", according to documentation, replaces the first one. Therefore it is not clear, why the first is still in crm! But both are quite old. The "two" is installable via composer, but both have their origin in PEAR. According to documentation, the purpose of this library was to give object oriented interface for standard php session_ functions. I do recommend to replace the library with something new or stick to native php session_ functions. There is a native object SessionHandler since php 5.4.0: https://www.php.net/manual/en/book.session.php

- mobileDetect - seems to be maintained on https://github.com/serbanghita/Mobile-Detect . Maybe I am missing something, but is it used anywhere?

- PHPExcel is not maintained for years - see https://github.com/PHPOffice/PHPExcel. It should be replaced with PhpSpreadsheet: https://github.com/PHPOffice/PhpSpreadsheet

**Comment by martinjur** [comment]
Replaced:
adodb
htmlpurifier
PHPMarkdown
Smarty

Removed:
mobileDetect
HTTP_Session
HTTP_Session2

**Comment by martinjur** [comment]
I've created separate issues for the rest - csrf-magic, google-api-php-client and PHPExcel, because there is more work with each.
